### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by asdxzcvbf13** [HamedAp/Tapswap-Cinema#14]
It doesn't work, I kind of did everything right. I launched a tap swipe, turned off the Internet, refreshed the page and copied the link, pasted it into the browser 
 I followed it, installed a new script and added tampermonkey.js in the extension, but I just have an endless download, nothing happens

**Comment by HamedAp** [comment]
did your link of tapswap opened in browser ?

**Comment by asdxzcvbf13** [comment]
> did your link of tapswap opened in browser ?

no, the link that I copied in the phone, it did not open, there was an endless download (a circle is spinning in the middle of the screen

**Comment by HamedAp** [comment]
> > did your link of tapswap opened in browser ?
> 
> no, the link that I copied in the phone, it did not open, there was an endless download (a circle is spinning in the middle of the screen

You did not copy well .
Try to select all text ( include error ...) 
Because some text of your link is not copy if you click on link and select copy

**Comment by asdxzcvbf13** [comment]
> > > did your link of tapswap opened in browser ?
> > 
> > 
> > no, the link that I copied in the phone, it did not open, there was an endless download (a circle is spinning in the middle of the screen
> 
> You did not copy well . Try to select all text ( include error ...) Because some text of your link is not copy if you click on link and select copy

do you mean copy all the text on the page, and then just delete the text and leave only the link? Because if you don't click "select all", then only part of the link is copied, and the rest is not visible?

**Comment by asdxzcvbf13** [comment]
> > > открылась ли ваша ссылка TapSwap в браузере?
> > 
> > 
> > нет, ссылка, которую я скопировал в телефоне, не открылась, была бесконечная загрузка (крутится круг посередине экрана
> 
> Вы не скопировали как следует. Попробуйте выделить весь текст (включая ошибку ...) Потому что часть текста вашей ссылки не копируется, если вы нажмете на ссылку и выберете копировать

now I have done everything correctly, copied the link completely, now the application has opened in the browser, then I installed the script, but for some reason my tasks were not completed, nothing has changed

**Comment by HamedAp** [comment]
> > > > открылась ли ваша ссылка TapSwap в браузере?
> > > 
> > > 
> > > нет, ссылка, которую я скопировал в телефоне, не открылась, была бесконечная загрузка (крутится круг посередине экрана
> > 
> > 
> > Вы не скопировали как следует. Попробуйте выделить весь текст (включая ошибку ...) Потому что часть текста вашей ссылки не копируется, если вы нажмете на ссылку и выберете копировать
> 
> now I have done everything correctly, copied the link completely, now the application has opened in the browser, then I installed the script, but for some reason my tasks were not completed, nothing has changed

Does it goes for opening task automatic ?
I mean open and back and go next task ?
I didnot added yesterday task . I will add answers soon .

**Comment by asdxzcvbf13** [comment]
> > > > > открылась ли ваша ссылка TapSwap в браузере?
> > > > 
> > > > 
> > > > нет, ссылка, я скопировал в который телефон, не открылась, была бесконечная загрузка (крутится круг посередине экрана
> > > 
> > > 
> > > Вы не скопировали, как следует. попробуйте удалить весь текст (исключая ошибку ...) Потому что часть текста вашей ссылки не копируется, если вы нажмете на ссылку и выберете скопировать
> > 
> > 
> > теперь я все сделал правильно, скопировал ссылку полностью, теперь приложение открылось в браузере, затем я установил скрипт, но по какой-то причине мои задачи не были выполнены, ничего не изменилось
> 
> Это относится к автоматическому открытию задачи? Я имею в виду открыть и вернуться и перейти к следующей задаче? Я не добавлял вчерашнюю задачу. Я добавлю ответы в ближайшее время.

Thanks, I've sorted everything out)
