### ISSUE TITLE
"High Paying Micro Task Websites": "custody" > cpustody

### ISSUE THREAD

**Issue by Lastnet0709** [HamedAp/Tapswap-Cinema#2]
![Screenshot_135](https://github.com/user-attachments/assets/98184cc8-12fe-43c0-bdc1-71b7fb6c75f5)

**Comment by oboroccv** [comment]
![image](https://github.com/user-attachments/assets/e0da7c2e-e5fc-4fe0-ab93-83897406e4c4)

**Comment by HamedAp** [comment]
Thanks . Fixed it . ❤️
