### ISSUE TITLE
خطا در انجام اسکریپت

### ISSUE THREAD

**Issue by alisako** [HamedAp/Tapswap-Cinema#7]
![Screenshot_۲۰۲۴-۰۹-۲۷-۰۳-۱۰-۲۹-۲۷۷_com microsoft rdc androidx](https://github.com/user-attachments/assets/3c3b39a9-c7e1-4ba1-8026-64140daeef19)
سلام من با این خطا ربرو میشیم یعنی چه؟؟

**Comment by HamedAp** [comment]
سلام این خطا نیست . اسم و ای دی تلگرام رو بالا نشون میده . کلا لود نمیشه بخش تسک ها ؟

**Comment by alisako** [comment]
ن هیچی نشون نمیده

**Comment by alisako** [comment]
من با سرور مجازی انجام میدم مشکلی نی؟؟

**Comment by HamedAp** [comment]
نباید مشکلی باشه .
F12 رو بزنین .
در تب کنسول ببینین خطا میده ؟
