### ISSUE TITLE
تسک selling your dreams

### ISSUE THREAD

**Issue by SLVRMGC** [HamedAp/Tapswap-Cinema#9]
توی تسک selling your dreams به باگ میخوره و کد رو اشتباه میزنه و گیر میکنه
کد درست اینه
geforce

**Comment by HamedAp** [comment]
حل شد ؟

**Comment by HamedAp** [comment]
این کد هارو مجبوریم دستی بزنیم فعلا . 
تا ما نزنیم اونجوری خطا میده . 
حداکثر با 1 ساعت تاخیر میزنیم معمولا .
